Added Rspec for enumerable methods
ghamtre/enumerable pull request #7
Opened 2020-04-06 20:38 UTC by bettercallazamat

We added Rspec for enumerable methods following the instructions required by [Microverse Curriculum ](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59566098/).

Any new changes will be documented and pushed on this pull request.

2020-04-06 23:53 UTC, majovanilla requested changes
Hey team, 👋

## You did an *amazing*🌟 ✨ job on this project! 👊🏻  💯
There are still some changes 👇 you need to implement to approve this request 🔍

### Required Changes: ✍️

- Include the instructions to test your files on your ReadMe
- Check the comments above.
## Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes

2020-04-06 23:53 UTC, majovanilla commented on spec/main_spec.rb
> +
You should test other types of enumerables: ranges, array of strings, a block of code.

2020-04-06 23:53 UTC, majovanilla commented on spec/main_spec.rb
> +    end
Include a test to check if the index it's working correctly.

2020-04-06 23:53 UTC, majovanilla commented on spec/main_spec.rb
> +    end
Try this with other types of enumerable as suggested.

2020-04-06 23:53 UTC, majovanilla commented on spec/main_spec.rb
> +  end
Good job considering negative cases

2020-04-06 23:53 UTC, majovanilla commented on spec/main_spec.rb
> +  end
Include a test to check the negative case.

2020-04-06 23:53 UTC, majovanilla commented on spec/main_spec.rb
> +  end
Chech this method with other types of enumerable.

2020-04-07 19:59 UTC, shshamim63 requested changes
## Status :1234:  Changes Required :1234: 
___
Hi @bettercallazamat and @ghamtre :wave: ,
Awesome job :clap: You have covered all the changes asked by the previous review except one major one. Which is currently asking blocking me to approve this project now. Check the comment below.
___
### :spades: Mandatory Changes :spades: 
___
1. As the previous reviewer mentioned, still I cant not see any instruction about how to execute the test cases. Now the question is why I should add it? The first thing a user looks at a repository is the readme.  So if it does not contain all the core information related to the project, the user will lose interest. So the core features of this project are enumerable methods and RSpec. So it will be great if you add it to the readme.
___
### :clubs: Optional Changes :clubs: 
___
1. You can check your methods with the actual methods. I have added an example. Obviously there are thousands of ways to cover it. But comparing with the actual seems more valid to me.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain

2020-04-07 19:59 UTC, shshamim63 commented on spec/main_spec.rb
> +      end
[Optional]
We want our my_each to work exactly to each method right? So why not check it with it? We can transform the test case something like this->
```ruby
it 'push each value to the result array' do
    expected = []
    array.my_each { |x| result.push(x) }
    current_result = expected.dup
    array.each { |x| result.push(x) }
    expect(current_result).to eq(expected)
end
```

2020-04-07 20:46 UTC, stratospherique approved these changes
### Great Job implementing the suggested changes :clap: :clap: Congrats, your project is approved :heavy_check_mark: You may merge :+1: :+1: 

Keep up the good work :muscle: 
**_Ahmed Mahfoudh_**

2020-04-07 21:02 UTC, merged